/*
 * Baka.java
 *
 * Created on 2007/12/17, 19:10
 */

package open.dolphin.impl.schema;

import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;
import open.dolphin.client.ClientContext;

/**
 *
 * @author  kazm
 */
public class SimpleCanvas extends javax.swing.JDialog {
    
    /** Creates new form Baka
     * @param parent
     * @param title
     * @param modal */
    public SimpleCanvas(java.awt.Frame parent, String title, boolean modal) {
        super(parent, title, modal);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lineBtn = new javax.swing.JToggleButton();
        rectBtn = new javax.swing.JToggleButton();
        ovalBtn = new javax.swing.JToggleButton();
        polyBtn = new javax.swing.JToggleButton();
        rectFillBtn = new javax.swing.JToggleButton();
        ovalFillBtn = new javax.swing.JToggleButton();
        polyFillBtn = new javax.swing.JToggleButton();
        textBtn = new javax.swing.JToggleButton();
        lineWidthCombo = new javax.swing.JComboBox();
        colorBtn = new javax.swing.JButton();
        undoBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        canvasPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        titleFld = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        roleCombo = new javax.swing.JComboBox();
        okBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        selectBtn = new javax.swing.JToggleButton();
        openPathBtn = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        java.util.ResourceBundle bundle = ClientContext.getMyBundle(SimpleCanvas.class);
        
        lineBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/open/dolphin/impl/schema/resources/LineOff.gif"))); // NOI18N
        lineBtn.setToolTipText(bundle.getString("toolTipText.line"));
        lineBtn.setMargin(new java.awt.Insets(4, 4, 3, 3));

        rectBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/open/dolphin/impl/schema/resources/RectOff.gif"))); // NOI18N
        rectBtn.setToolTipText(bundle.getString("tooltipText.squre"));
        rectBtn.setMargin(new java.awt.Insets(4, 4, 3, 3));

        ovalBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/open/dolphin/impl/schema/resources/OvalOff.gif"))); // NOI18N
        ovalBtn.setToolTipText(bundle.getString("toolTipText.oval"));
        ovalBtn.setMargin(new java.awt.Insets(4, 4, 3, 3));

        polyBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/open/dolphin/impl/schema/resources/PolyOff.gif"))); // NOI18N
        polyBtn.setToolTipText(bundle.getString("toolTipText.closedPath"));
        polyBtn.setMargin(new java.awt.Insets(4, 4, 3, 3));

        rectFillBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/open/dolphin/impl/schema/resources/FillRectOff.gif"))); // NOI18N
        rectFillBtn.setToolTipText(bundle.getString("toolTipText.filledSqure"));
        rectFillBtn.setMargin(new java.awt.Insets(4, 4, 3, 3));

        ovalFillBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/open/dolphin/impl/schema/resources/FillOvalOff.gif"))); // NOI18N
        ovalFillBtn.setToolTipText(bundle.getString("toolTipText.filledOval"));
        ovalFillBtn.setMargin(new java.awt.Insets(4, 4, 3, 3));

        polyFillBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/open/dolphin/impl/schema/resources/FillPolyOff.gif"))); // NOI18N
        polyFillBtn.setToolTipText(bundle.getString("tooltipText.filledPolygon"));
        polyFillBtn.setMargin(new java.awt.Insets(4, 4, 3, 3));

        textBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/open/dolphin/impl/schema/resources/TextOff.gif"))); // NOI18N
        textBtn.setToolTipText(bundle.getString("toolTipText.textInput"));
        textBtn.setMargin(new java.awt.Insets(4, 4, 3, 3));

        lineWidthCombo.setToolTipText(bundle.getString("toolTipText.selectLineWidth"));

        colorBtn.setToolTipText(bundle.getString("toolTipText.selectFillColor"));
        colorBtn.setMaximumSize(new java.awt.Dimension(32, 29));
        colorBtn.setMinimumSize(new java.awt.Dimension(32, 29));
        colorBtn.setPreferredSize(new java.awt.Dimension(32, 29));

        undoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/open/dolphin/impl/schema/resources/undo_24.gif"))); // NOI18N
        undoBtn.setToolTipText(bundle.getString("toolTipText.redo"));

        clearBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/open/dolphin/impl/schema/resources/remov_24.gif"))); // NOI18N
        clearBtn.setToolTipText(bundle.getString("toolTipText.clear"));

        canvasPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText(bundle.getString("label.title"));

        jLabel2.setText(bundle.getString("label.use"));

        roleCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
            bundle.getString("labTest"), 
            bundle.getString("endoScopy"), 
            bundle.getString("xRay"), 
            bundle.getString("upperGi"), 
            bundle.getString("baEnema"), 
            bundle.getString("ctScan"), 
            bundle.getString("mri"), 
            bundle.getString("riInVivo"), 
            bundle.getString("angioGraphy"), 
            bundle.getString("otherRadiology"), 
            bundle.getString("echo"), 
            bundle.getString("ecg"), 
            bundle.getString("eeg"), 
            bundle.getString("emg"), 
            bundle.getString("pcg"), 
            bundle.getString("pulmonaryFunction"), 
            bundle.getString("otherPhysiologicalTest"), 
            bundle.getString("prescription"), 
            bundle.getString("vitalSign"), 
            bundle.getString("physicalExam"), 
            bundle.getString("anesthesiaCourse"), 
            bundle.getString("pathology"), 
            bundle.getString("surgicalFigure"), 
            bundle.getString("referencePaper"), 
            bundle.getString("referenceFigure"), 
            bundle.getString("treatment"), 
            bundle.getString("other") }));

        okBtn.setText(bundle.getString("toolTipText.insertIntoKarte"));

        cancelBtn.setText(bundle.getString("toolTipText.undo"));

        selectBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/open/dolphin/impl/schema/resources/move_24.gif"))); // NOI18N
        selectBtn.setToolTipText(bundle.getString("toolTipText.move"));

        openPathBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/open/dolphin/impl/schema/resources/PolyLineOff.gif"))); // NOI18N
        openPathBtn.setToolTipText(bundle.getString("toolTipeText.openedPath"));
        openPathBtn.setMargin(new java.awt.Insets(4, 4, 3, 3));

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lineBtn)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rectBtn)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ovalBtn)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(openPathBtn)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(polyBtn)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rectFillBtn)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ovalFillBtn)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(polyFillBtn)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textBtn)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lineWidthCombo, GroupLayout.PREFERRED_SIZE, 78, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(colorBtn, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(selectBtn)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(undoBtn)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clearBtn)
                        .addGap(18, 18, 18))
                    .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(titleFld, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(roleCombo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelBtn)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(okBtn))
                    .addComponent(canvasPanel, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lineBtn)
                    .addComponent(rectBtn)
                    .addComponent(ovalBtn)
                    .addComponent(openPathBtn)
                    .addComponent(polyBtn)
                    .addComponent(rectFillBtn)
                    .addComponent(ovalFillBtn)
                    .addComponent(polyFillBtn)
                    .addComponent(textBtn)
                    .addComponent(colorBtn, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(undoBtn)
                    .addComponent(selectBtn)
                    .addComponent(clearBtn)
                    .addComponent(lineWidthCombo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(canvasPanel, GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(titleFld, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(roleCombo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBtn)
                    .addComponent(okBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    
    // Variables declaration - do not modify                     
    private javax.swing.JButton cancelBtn;
    private javax.swing.JPanel canvasPanel;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton colorBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToggleButton lineBtn;
    private javax.swing.JComboBox lineWidthCombo;
    private javax.swing.JButton okBtn;
    private javax.swing.JToggleButton openPathBtn;
    private javax.swing.JToggleButton ovalBtn;
    private javax.swing.JToggleButton ovalFillBtn;
    private javax.swing.JToggleButton polyBtn;
    private javax.swing.JToggleButton polyFillBtn;
    private javax.swing.JToggleButton rectBtn;
    private javax.swing.JToggleButton rectFillBtn;
    private javax.swing.JComboBox roleCombo;
    private javax.swing.JToggleButton selectBtn;
    private javax.swing.JToggleButton textBtn;
    private javax.swing.JTextField titleFld;
    private javax.swing.JButton undoBtn;
    // End of variables declaration                   

    public javax.swing.JButton getCancelBtn() {
        return cancelBtn;
    }

    public javax.swing.JPanel getCanvasPanel() {
        return canvasPanel;
    }

    public javax.swing.JButton getClearBtn() {
        return clearBtn;
    }

    public javax.swing.JButton getColorBtn() {
        return colorBtn;
    }

    public javax.swing.JToggleButton getLineBtn() {
        return lineBtn;
    }

    public javax.swing.JComboBox getLineWidthCombo() {
        return lineWidthCombo;
    }

    public javax.swing.JButton getOkBtn() {
        return okBtn;
    }

    public javax.swing.JToggleButton getOvalBtn() {
        return ovalBtn;
    }

    public javax.swing.JToggleButton getOvalFillBtn() {
        return ovalFillBtn;
    }

    public javax.swing.JToggleButton getOpenPathBtn() {
        return openPathBtn;
    }

    public javax.swing.JToggleButton getPolyBtn() {
        return polyBtn;
    }

    public javax.swing.JToggleButton getPolyFillBtn() {
        return polyFillBtn;
    }

    public javax.swing.JToggleButton getRectBtn() {
        return rectBtn;
    }

    public javax.swing.JToggleButton getRectFillBtn() {
        return rectFillBtn;
    }

    public javax.swing.JComboBox getRoleCombo() {
        return roleCombo;
    }

    public javax.swing.JToggleButton getSelectBtn() {
        return selectBtn;
    }

    public javax.swing.JToggleButton getTextBtn() {
        return textBtn;
    }

    public javax.swing.JTextField getTitleFld() {
        return titleFld;
    }

    public javax.swing.JButton getUndoBtn() {
        return undoBtn;
    }
    
}
