/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LoginPanel.java
 *
 * Created on 2011/06/17, 9:39:25
 */

package open.dolphin.impl.login;

/**
 *
 * @author kazushi
 */
public class LoginPanel extends javax.swing.JPanel {

    /** Creates new form LoginPanel */
    public LoginPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        userIdLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        userIdFld = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        cancelBtn = new javax.swing.JButton();
        settingBtn = new javax.swing.JButton();
        loginBtn = new javax.swing.JButton();
        progressBar = new javax.swing.JProgressBar();
        passwordFld = new javax.swing.JPasswordField();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/open/dolphin/resources/images/splash.jpg"))); // NOI18N

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("open/dolphin/impl/login/resources/LoginPanel"); // NOI18N
        userIdLabel.setText(bundle.getString("userIdLabel.text")); // NOI18N

        passwordLabel.setText(bundle.getString("passwordLabel.text")); // NOI18N

        jPanel1.setMinimumSize(new java.awt.Dimension(258, 29));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 2, 0));

        cancelBtn.setText(bundle.getString("cancelBtn.text")); // NOI18N
        cancelBtn.setToolTipText(""); // NOI18N
        jPanel1.add(cancelBtn);

        settingBtn.setText(bundle.getString("settingBtn.text")); // NOI18N
        settingBtn.setToolTipText(""); // NOI18N
        jPanel1.add(settingBtn);

        loginBtn.setText(bundle.getString("loginBtn.text")); // NOI18N
        jPanel1.add(loginBtn);

        progressBar.setPreferredSize(new java.awt.Dimension(146, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userIdLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(passwordLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userIdFld)
                            .addComponent(passwordFld)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {passwordFld, progressBar, userIdFld});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userIdLabel)
                            .addComponent(userIdFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passwordLabel)
                            .addComponent(passwordFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField passwordFld;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JButton settingBtn;
    private javax.swing.JTextField userIdFld;
    private javax.swing.JLabel userIdLabel;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getCancelBtn() {
        return cancelBtn;
    }

    public javax.swing.JButton getLoginBtn() {
        return loginBtn;
    }

    public javax.swing.JPasswordField getPasswordField() {
        return passwordFld;
    }

    public javax.swing.JProgressBar getProgressBar() {
        return progressBar;
    }

    public javax.swing.JButton getSettingBtn() {
        return settingBtn;
    }

    public javax.swing.JTextField getUserIdField() {
        return userIdFld;
    }

    public javax.swing.JComboBox getFacilityCmb() {
        return null;
    }
    
//s.oh^ RSS対応
    public javax.swing.JLabel getLogoLabel() {
        return jLabel1;
    }
//s.oh$
}
