/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package open.dolphin.hiro;

/**
 *
 * @author kazushi
 */
public class PostConfirmPanel extends javax.swing.JPanel {

    /**
     * Creates new form PostConfirmPanel
     */
    public PostConfirmPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chkHomeMedical = new javax.swing.JCheckBox();
        chkUseDrugInfo = new javax.swing.JCheckBox();
        lblNarcoticsPractitioner = new javax.swing.JLabel();
        narcoticsPractitioner = new javax.swing.JTextField();
        lblUseDrugId = new javax.swing.JLabel();
        useDrugId = new javax.swing.JTextField();
        chkPatientInfo = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        tfPeriod = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        facilitCodeField = new javax.swing.JTextField();
        generalChk = new javax.swing.JCheckBox();

        chkHomeMedical.setText("備考欄に「在宅」を記入");

        chkUseDrugInfo.setText("麻薬施用者免許番号を転帰");

        lblNarcoticsPractitioner.setText("麻薬施用者:");

        lblUseDrugId.setText("麻薬施用者免許番号:");

        useDrugId.setToolTipText("ツールメニューのプロフィール変更で登録します。");

        chkPatientInfo.setText("患者氏名、住所を転帰");

        jLabel3.setText("使用期間:");

        tfPeriod.setToolTipText("右クリックでカレンダーがポップアップします。");

        jLabel1.setText("保険医療機関コード:");

        facilitCodeField.setEditable(false);
        facilitCodeField.setToolTipText("ツールメニューの医療機関コード読み込みから取得できます。");

        generalChk.setText("一般名で出力する");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkPatientInfo)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(facilitCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(chkHomeMedical)
                    .addComponent(chkUseDrugInfo)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblUseDrugId)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(useDrugId))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNarcoticsPractitioner)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(narcoticsPractitioner, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(generalChk))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkHomeMedical)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkUseDrugInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNarcoticsPractitioner)
                    .addComponent(narcoticsPractitioner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUseDrugId)
                    .addComponent(useDrugId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkPatientInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(facilitCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generalChk)
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkHomeMedical;
    private javax.swing.JCheckBox chkPatientInfo;
    private javax.swing.JCheckBox chkUseDrugInfo;
    private javax.swing.JTextField facilitCodeField;
    private javax.swing.JCheckBox generalChk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblNarcoticsPractitioner;
    private javax.swing.JLabel lblUseDrugId;
    private javax.swing.JTextField narcoticsPractitioner;
    private javax.swing.JTextField tfPeriod;
    private javax.swing.JTextField useDrugId;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JCheckBox getChkHomeMedical() {
        return chkHomeMedical;
    }

    public javax.swing.JCheckBox getChkPatientInfo() {
        return chkPatientInfo;
    }

    public javax.swing.JCheckBox getChkUseDrugInfo() {
        return chkUseDrugInfo;
    }

    public javax.swing.JTextField getNarcoticsPractitioner() {
        return narcoticsPractitioner;
    }

    public javax.swing.JTextField getTfPeriod() {
        return tfPeriod;
    }

    public javax.swing.JTextField getUseDrugId() {
        return useDrugId;
    }

    public javax.swing.JLabel getLblNarcoticsPractitioner() {
        return lblNarcoticsPractitioner;
    }

    public javax.swing.JLabel getLblUseDrugId() {
        return lblUseDrugId;
    }

    public javax.swing.JTextField getFacilitCodeField() {
        return facilitCodeField;
    }

    public javax.swing.JCheckBox getGeneralChk() {
        return generalChk;
    }
}
